### ISSUE TITLE
acrescentar screenshot

### ISSUE THREAD

**Issue by vcwild** [Ias4g/blood-donation#1]
Boa tarde dev, gostei do seu projeto. Que tal acrescentar um screenshot da landing page do seu site no README?

**Comment by Ias4g** [comment]
### Fala dev, @vcwild!
Como tinha me sugerido, já estar no arquivo **README.md** as informações.

[Ver atualizações >>](https://github.com/Ias4g/blood-donation/blob/master/README.md)

![GIthub-02](https://user-images.githubusercontent.com/62667424/78938201-2e59cf00-7a88-11ea-997f-2bcd191d4cee.jpg)

* Vejam meus projetos [GitHub](https://github.com/Ias4g)
* Sigam-me no [Instagram](https://www.instagram.com/oficial_emunah/)
